services:
  config-generator:
    build: ./config-generator
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - httpd-config:/etc/docker-gen/results:rw
    environment:
      - TOPDOMAIN=$TOPDOMAIN
      - DEFAULT_REDIRECT_TO_TOPDOMAIN=$DEFAULT_REDIRECT_TO_TOPDOMAIN
      - REDIRECT_TO_SECURE=$REDIRECT_TO_SECURE
      - CUSTOM_CONFIG=$CUSTOM_CONFIG
    restart: always
  http-daemon:
    build: ./http-daemon
    volumes:
      - httpd-config:/usr/local/apache2/web-proxy:ro
      - ${HTDOCS_DIRECTORY:-./html}:/usr/local/apache2/htdocs:ro
    ports:
      - ${HTTP_PORT:-80}:80
    restart: always
volumes:
  httpd-config:
    driver: local